const testData = [
  {
    title: "bed",
    description: "this bed is awesome",
    id: 1,
    isDiscount: true,
    discountPercentage: 10,
    price: 20,
    rating: 3,
    category: "furniture",
    thumbnail: "test.jpg",
    shippingInformation: "1-2 days",
    availabilityStatus: "In stock",
    reviews: [
      {
        reviewerName: "Jack",
        rating: 4,
        comment: "Very good",
      },
    ],
  },
  {
    title: "chair",
    description: "quality product",
    id: 2,
    isDiscount: false,
    discountPercentage: 5,
    price: 10,
    rating: 4,
    category: "furniture",
    thumbnail: "test.jpg",
    shippingInformation: "3-4 days",
    availabilityStatus: "Low stock",
    reviews: [
      {
        reviewerName: "Will",
        rating: 5,
        comment: "Awesome",
      },
    ],
  },
  {
    title: "table",
    description: "sturdy table",
    id: 3,
    isDiscount: false,
    discountPercentage: 7,
    price: 30,
    rating: 5,
    category: "furniture",
    thumbnail: "test.jpg",
    shippingInformation: "1-2 weeks",
    availabilityStatus: "In stock",
    reviews: [
      {
        reviewerName: "Susan",
        rating: 3,
        comment: "Average",
      },
    ],
  },
  {
    title: "apple",
    description: "fresh and tasty",
    id: 4,
    isDiscount: false,
    discountPercentage: 7,
    price: 2.5,
    rating: 4.2,
    category: "groceries",
    thumbnail: "test.jpg",
    shippingInformation: "overnight",
    availabilityStatus: "In stock",
    reviews: [
      {
        reviewerName: "Mike",
        rating: 4,
        comment: "Tasty",
      },
    ],
  },
  {
    title: "potato",
    description: "Tasty potatoes",
    id: 5,
    isDiscount: false,
    discountPercentage: 10,
    price: 4.6,
    rating: 3.7,
    category: "groceries",
    thumbnail: "test.jpg",
    shippingInformation: "2 days",
    availabilityStatus: "In stock",
    reviews: [
      {
        reviewerName: "Anna",
        rating: 5,
        comment: "Really good",
      },
    ],
  },
  {
    title: "Lipstick",
    description: "quality product",
    id: 6,
    isDiscount: true,
    discountPercentage: 12,
    price: 15.3,
    rating: 5,
    category: "beauty",
    thumbnail: "test.jpg",
    shippingInformation: "1 week",
    availabilityStatus: "In stock",
    reviews: [
      {
        reviewerName: "Scarlett",
        rating: 4,
        comment: "Decent",
      },
    ],
  },
  {
    title: "Red nail polish",
    description: "Really polished product",
    id: 7,
    isDiscount: false,
    discountPercentage: 25,
    price: 50,
    rating: 4.6,
    category: "beauty",
    thumbnail: "test.jpg",
    shippingInformation: "3 days",
    availabilityStatus: "In stock",
    reviews: [
      {
        reviewerName: "Susan",
        rating: 4,
        comment: "Awesome",
      },
    ],
  },
  {
    title: "Elegante",
    description: "Only fragrance you will ever need",
    id: 8,
    isDiscount: false,
    discountPercentage: 10,
    price: 40,
    rating: 4.6,
    category: "fragrances",
    thumbnail: "test.jpg",
    shippingInformation: "1-2 weeks",
    availabilityStatus: "In stock",
    reviews: [
      {
        reviewerName: "John",
        rating: 5,
        comment: "Top quality",
      },
    ],
  },
  {
    title: "ScentX",
    description: "Perfect for evening occasions",
    id: 9,
    isDiscount: false,
    discountPercentage: 10,
    price: 60,
    rating: 4.2,
    category: "fragrances",
    thumbnail: "test.jpg",
    shippingInformation: "1 week",
    availabilityStatus: "Low stock",
    reviews: [
      {
        reviewerName: "Anthony",
        rating: 5,
        comment: "The Best",
      },
    ],
  },
];

const testCart = [
  {
    title: "chair",
    id: 2,
    isDiscount: false,
    discountPercentage: 5,
    category: "furniture",
    image: "test.jpg",
    price: 10,
    quantity: 2,
  },
  {
    title: "potato",
    id: 5,
    isDiscount: false,
    discountPercentage: 10,
    category: "groceries",
    image: "test.jpg",
    price: 4.6,
    quantity: 5,
  },
];

export { testData, testCart };
